name: Test

on: pull_request

jobs:
  test:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: 3.6
            tox: py36
          - python: 3.7
            tox: py37
          - python: 3.8
            tox: py38
      fail-fast: false
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install pip dependencies
        run: pip install -U pip tox virtualenv
      - name: Test packaging
        run: tox
        env:
          TOXENV: ${{ matrix.tox }}

  check_for_differences:
    name: Check for upstream differences
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Check for upstream differences
        run: bin/check_for_differences
        env:
          TEST_ONLY: true
